/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface RaribleCloneFactoryInterface extends utils.Interface {
  functions: {
    "deployProxyByImplementation(address,bytes,bytes32)": FunctionFragment;
    "deployProxyByImplementationV2(address,bytes,bytes32,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "deployProxyByImplementation"
      | "deployProxyByImplementationV2"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployProxyByImplementation",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deployProxyByImplementationV2",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployProxyByImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployProxyByImplementationV2",
    data: BytesLike
  ): Result;

  events: {
    "ProxyDeployed(address,address,address)": EventFragment;
    "ProxyDeployedV2(address,address,address,bytes32,bytes,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProxyDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProxyDeployedV2"): EventFragment;
}

export interface ProxyDeployedEventObject {
  implementation: string;
  proxy: string;
  deployer: string;
}
export type ProxyDeployedEvent = TypedEvent<
  [string, string, string],
  ProxyDeployedEventObject
>;

export type ProxyDeployedEventFilter = TypedEventFilter<ProxyDeployedEvent>;

export interface ProxyDeployedV2EventObject {
  implementation: string;
  proxy: string;
  deployer: string;
  inputSalt: string;
  data: string;
  extraData: string;
}
export type ProxyDeployedV2Event = TypedEvent<
  [string, string, string, string, string, string],
  ProxyDeployedV2EventObject
>;

export type ProxyDeployedV2EventFilter = TypedEventFilter<ProxyDeployedV2Event>;

export interface RaribleCloneFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RaribleCloneFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployProxyByImplementation(
      _implementation: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      _salt: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deployProxyByImplementationV2(
      implementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      salt: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  deployProxyByImplementation(
    _implementation: PromiseOrValue<string>,
    _data: PromiseOrValue<BytesLike>,
    _salt: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deployProxyByImplementationV2(
    implementation: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    salt: PromiseOrValue<BytesLike>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    deployProxyByImplementation(
      _implementation: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      _salt: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    deployProxyByImplementationV2(
      implementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      salt: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "ProxyDeployed(address,address,address)"(
      implementation?: PromiseOrValue<string> | null,
      proxy?: null,
      deployer?: PromiseOrValue<string> | null
    ): ProxyDeployedEventFilter;
    ProxyDeployed(
      implementation?: PromiseOrValue<string> | null,
      proxy?: null,
      deployer?: PromiseOrValue<string> | null
    ): ProxyDeployedEventFilter;

    "ProxyDeployedV2(address,address,address,bytes32,bytes,bytes)"(
      implementation?: PromiseOrValue<string> | null,
      proxy?: PromiseOrValue<string> | null,
      deployer?: PromiseOrValue<string> | null,
      inputSalt?: null,
      data?: null,
      extraData?: null
    ): ProxyDeployedV2EventFilter;
    ProxyDeployedV2(
      implementation?: PromiseOrValue<string> | null,
      proxy?: PromiseOrValue<string> | null,
      deployer?: PromiseOrValue<string> | null,
      inputSalt?: null,
      data?: null,
      extraData?: null
    ): ProxyDeployedV2EventFilter;
  };

  estimateGas: {
    deployProxyByImplementation(
      _implementation: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      _salt: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deployProxyByImplementationV2(
      implementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      salt: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployProxyByImplementation(
      _implementation: PromiseOrValue<string>,
      _data: PromiseOrValue<BytesLike>,
      _salt: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deployProxyByImplementationV2(
      implementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      salt: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
