"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.ERC1155Upgradeable__factory = exports.ERC1155Rarible__factory = exports.ERC1155Lazy__factory = exports.ERC1155DefaultApproval__factory = exports.ERC1155BurnableUpgradeable__factory = exports.ERC1155BaseURI__factory = exports.ERC1155Base__factory = exports.erc1155Meta = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.erc1155Meta = __importStar(require("./erc-1155-meta"));
var ERC1155Base__factory_1 = require("./ERC1155Base__factory");
Object.defineProperty(exports, "ERC1155Base__factory", { enumerable: true, get: function () { return ERC1155Base__factory_1.ERC1155Base__factory; } });
var ERC1155BaseURI__factory_1 = require("./ERC1155BaseURI__factory");
Object.defineProperty(exports, "ERC1155BaseURI__factory", { enumerable: true, get: function () { return ERC1155BaseURI__factory_1.ERC1155BaseURI__factory; } });
var ERC1155BurnableUpgradeable__factory_1 = require("./ERC1155BurnableUpgradeable__factory");
Object.defineProperty(exports, "ERC1155BurnableUpgradeable__factory", { enumerable: true, get: function () { return ERC1155BurnableUpgradeable__factory_1.ERC1155BurnableUpgradeable__factory; } });
var ERC1155DefaultApproval__factory_1 = require("./ERC1155DefaultApproval__factory");
Object.defineProperty(exports, "ERC1155DefaultApproval__factory", { enumerable: true, get: function () { return ERC1155DefaultApproval__factory_1.ERC1155DefaultApproval__factory; } });
var ERC1155Lazy__factory_1 = require("./ERC1155Lazy__factory");
Object.defineProperty(exports, "ERC1155Lazy__factory", { enumerable: true, get: function () { return ERC1155Lazy__factory_1.ERC1155Lazy__factory; } });
var ERC1155Rarible__factory_1 = require("./ERC1155Rarible__factory");
Object.defineProperty(exports, "ERC1155Rarible__factory", { enumerable: true, get: function () { return ERC1155Rarible__factory_1.ERC1155Rarible__factory; } });
var ERC1155Upgradeable__factory_1 = require("./ERC1155Upgradeable__factory");
Object.defineProperty(exports, "ERC1155Upgradeable__factory", { enumerable: true, get: function () { return ERC1155Upgradeable__factory_1.ERC1155Upgradeable__factory; } });
//# sourceMappingURL=index.js.map