/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  LibClone,
  LibCloneInterface,
} from "../../../../../lib/solady/src/utils/LibClone";

const _abi = [
  {
    inputs: [],
    name: "DeploymentFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "ETHTransferFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "SaltDoesNotStartWith",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220719f0e848e844023cfa2dbc9c00e644cad026bf1d23c2661a954ac41aab98e0764736f6c63430008140033";

type LibCloneConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LibCloneConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LibClone__factory extends ContractFactory {
  constructor(...args: LibCloneConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<LibClone> {
    return super.deploy(overrides || {}) as Promise<LibClone>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): LibClone {
    return super.attach(address) as LibClone;
  }
  override connect(signer: Signer): LibClone__factory {
    return super.connect(signer) as LibClone__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibCloneInterface {
    return new utils.Interface(_abi) as LibCloneInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibClone {
    return new Contract(address, _abi, signerOrProvider) as LibClone;
  }
}
