/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MinterAccessControlTestV1__factory } from "./MinterAccessControlTestV1__factory";
export { MinterAccessControlTestV2__factory } from "./MinterAccessControlTestV2__factory";
