/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export declare namespace IClaimCondition {
  export type ClaimConditionStruct = {
    startTimestamp: PromiseOrValue<BigNumberish>;
    maxClaimableSupply: PromiseOrValue<BigNumberish>;
    supplyClaimed: PromiseOrValue<BigNumberish>;
    quantityLimitPerWallet: PromiseOrValue<BigNumberish>;
    merkleRoot: PromiseOrValue<BytesLike>;
    pricePerToken: PromiseOrValue<BigNumberish>;
    currency: PromiseOrValue<string>;
    metadata: PromiseOrValue<string>;
  };

  export type ClaimConditionStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    string,
    string
  ] & {
    startTimestamp: BigNumber;
    maxClaimableSupply: BigNumber;
    supplyClaimed: BigNumber;
    quantityLimitPerWallet: BigNumber;
    merkleRoot: string;
    pricePerToken: BigNumber;
    currency: string;
    metadata: string;
  };
}

export declare namespace IDrop1155 {
  export type AllowlistProofStruct = {
    proof: PromiseOrValue<BytesLike>[];
    quantityLimitPerWallet: PromiseOrValue<BigNumberish>;
    pricePerToken: PromiseOrValue<BigNumberish>;
    currency: PromiseOrValue<string>;
  };

  export type AllowlistProofStructOutput = [
    string[],
    BigNumber,
    BigNumber,
    string
  ] & {
    proof: string[];
    quantityLimitPerWallet: BigNumber;
    pricePerToken: BigNumber;
    currency: string;
  };
}

export interface Drop1155Interface extends utils.Interface {
  functions: {
    "claim(address,uint256,uint256,address,uint256,(bytes32[],uint256,uint256,address),bytes)": FunctionFragment;
    "claimCondition(uint256)": FunctionFragment;
    "getActiveClaimConditionId(uint256)": FunctionFragment;
    "getClaimConditionById(uint256,uint256)": FunctionFragment;
    "getSupplyClaimedByWallet(uint256,uint256,address)": FunctionFragment;
    "setClaimConditions(uint256,(uint256,uint256,uint256,uint256,bytes32,uint256,address,string)[],bool)": FunctionFragment;
    "verifyClaim(uint256,address,uint256,uint256,address,uint256,(bytes32[],uint256,uint256,address))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "claim"
      | "claimCondition"
      | "getActiveClaimConditionId"
      | "getClaimConditionById"
      | "getSupplyClaimedByWallet"
      | "setClaimConditions"
      | "verifyClaim"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claim",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      IDrop1155.AllowlistProofStruct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claimCondition",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveClaimConditionId",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimConditionById",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupplyClaimedByWallet",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setClaimConditions",
    values: [
      PromiseOrValue<BigNumberish>,
      IClaimCondition.ClaimConditionStruct[],
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyClaim",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      IDrop1155.AllowlistProofStruct
    ]
  ): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveClaimConditionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimConditionById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupplyClaimedByWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setClaimConditions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyClaim",
    data: BytesLike
  ): Result;

  events: {
    "ClaimConditionsUpdated(uint256,tuple[],bool)": EventFragment;
    "TokensClaimed(uint256,address,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ClaimConditionsUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensClaimed"): EventFragment;
}

export interface ClaimConditionsUpdatedEventObject {
  tokenId: BigNumber;
  claimConditions: IClaimCondition.ClaimConditionStructOutput[];
  resetEligibility: boolean;
}
export type ClaimConditionsUpdatedEvent = TypedEvent<
  [BigNumber, IClaimCondition.ClaimConditionStructOutput[], boolean],
  ClaimConditionsUpdatedEventObject
>;

export type ClaimConditionsUpdatedEventFilter =
  TypedEventFilter<ClaimConditionsUpdatedEvent>;

export interface TokensClaimedEventObject {
  claimConditionIndex: BigNumber;
  claimer: string;
  receiver: string;
  tokenId: BigNumber;
  quantityClaimed: BigNumber;
}
export type TokensClaimedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, BigNumber],
  TokensClaimedEventObject
>;

export type TokensClaimedEventFilter = TypedEventFilter<TokensClaimedEvent>;

export interface Drop1155 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Drop1155Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    claim(
      _receiver: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _quantity: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      _pricePerToken: PromiseOrValue<BigNumberish>,
      _allowlistProof: IDrop1155.AllowlistProofStruct,
      _data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimCondition(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { currentStartId: BigNumber; count: BigNumber }
    >;

    getActiveClaimConditionId(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getClaimConditionById(
      _tokenId: PromiseOrValue<BigNumberish>,
      _conditionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [IClaimCondition.ClaimConditionStructOutput] & {
        condition: IClaimCondition.ClaimConditionStructOutput;
      }
    >;

    getSupplyClaimedByWallet(
      _tokenId: PromiseOrValue<BigNumberish>,
      _conditionId: PromiseOrValue<BigNumberish>,
      _claimer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { supplyClaimedByWallet: BigNumber }>;

    setClaimConditions(
      _tokenId: PromiseOrValue<BigNumberish>,
      _conditions: IClaimCondition.ClaimConditionStruct[],
      _resetClaimEligibility: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    verifyClaim(
      _conditionId: PromiseOrValue<BigNumberish>,
      _claimer: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _quantity: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      _pricePerToken: PromiseOrValue<BigNumberish>,
      _allowlistProof: IDrop1155.AllowlistProofStruct,
      overrides?: CallOverrides
    ): Promise<[boolean] & { isOverride: boolean }>;
  };

  claim(
    _receiver: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _quantity: PromiseOrValue<BigNumberish>,
    _currency: PromiseOrValue<string>,
    _pricePerToken: PromiseOrValue<BigNumberish>,
    _allowlistProof: IDrop1155.AllowlistProofStruct,
    _data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimCondition(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { currentStartId: BigNumber; count: BigNumber }
  >;

  getActiveClaimConditionId(
    _tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getClaimConditionById(
    _tokenId: PromiseOrValue<BigNumberish>,
    _conditionId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<IClaimCondition.ClaimConditionStructOutput>;

  getSupplyClaimedByWallet(
    _tokenId: PromiseOrValue<BigNumberish>,
    _conditionId: PromiseOrValue<BigNumberish>,
    _claimer: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setClaimConditions(
    _tokenId: PromiseOrValue<BigNumberish>,
    _conditions: IClaimCondition.ClaimConditionStruct[],
    _resetClaimEligibility: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  verifyClaim(
    _conditionId: PromiseOrValue<BigNumberish>,
    _claimer: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _quantity: PromiseOrValue<BigNumberish>,
    _currency: PromiseOrValue<string>,
    _pricePerToken: PromiseOrValue<BigNumberish>,
    _allowlistProof: IDrop1155.AllowlistProofStruct,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    claim(
      _receiver: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _quantity: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      _pricePerToken: PromiseOrValue<BigNumberish>,
      _allowlistProof: IDrop1155.AllowlistProofStruct,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    claimCondition(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { currentStartId: BigNumber; count: BigNumber }
    >;

    getActiveClaimConditionId(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getClaimConditionById(
      _tokenId: PromiseOrValue<BigNumberish>,
      _conditionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<IClaimCondition.ClaimConditionStructOutput>;

    getSupplyClaimedByWallet(
      _tokenId: PromiseOrValue<BigNumberish>,
      _conditionId: PromiseOrValue<BigNumberish>,
      _claimer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setClaimConditions(
      _tokenId: PromiseOrValue<BigNumberish>,
      _conditions: IClaimCondition.ClaimConditionStruct[],
      _resetClaimEligibility: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    verifyClaim(
      _conditionId: PromiseOrValue<BigNumberish>,
      _claimer: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _quantity: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      _pricePerToken: PromiseOrValue<BigNumberish>,
      _allowlistProof: IDrop1155.AllowlistProofStruct,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "ClaimConditionsUpdated(uint256,tuple[],bool)"(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      claimConditions?: null,
      resetEligibility?: null
    ): ClaimConditionsUpdatedEventFilter;
    ClaimConditionsUpdated(
      tokenId?: PromiseOrValue<BigNumberish> | null,
      claimConditions?: null,
      resetEligibility?: null
    ): ClaimConditionsUpdatedEventFilter;

    "TokensClaimed(uint256,address,address,uint256,uint256)"(
      claimConditionIndex?: PromiseOrValue<BigNumberish> | null,
      claimer?: PromiseOrValue<string> | null,
      receiver?: PromiseOrValue<string> | null,
      tokenId?: null,
      quantityClaimed?: null
    ): TokensClaimedEventFilter;
    TokensClaimed(
      claimConditionIndex?: PromiseOrValue<BigNumberish> | null,
      claimer?: PromiseOrValue<string> | null,
      receiver?: PromiseOrValue<string> | null,
      tokenId?: null,
      quantityClaimed?: null
    ): TokensClaimedEventFilter;
  };

  estimateGas: {
    claim(
      _receiver: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _quantity: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      _pricePerToken: PromiseOrValue<BigNumberish>,
      _allowlistProof: IDrop1155.AllowlistProofStruct,
      _data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimCondition(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getActiveClaimConditionId(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getClaimConditionById(
      _tokenId: PromiseOrValue<BigNumberish>,
      _conditionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSupplyClaimedByWallet(
      _tokenId: PromiseOrValue<BigNumberish>,
      _conditionId: PromiseOrValue<BigNumberish>,
      _claimer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setClaimConditions(
      _tokenId: PromiseOrValue<BigNumberish>,
      _conditions: IClaimCondition.ClaimConditionStruct[],
      _resetClaimEligibility: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    verifyClaim(
      _conditionId: PromiseOrValue<BigNumberish>,
      _claimer: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _quantity: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      _pricePerToken: PromiseOrValue<BigNumberish>,
      _allowlistProof: IDrop1155.AllowlistProofStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    claim(
      _receiver: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _quantity: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      _pricePerToken: PromiseOrValue<BigNumberish>,
      _allowlistProof: IDrop1155.AllowlistProofStruct,
      _data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimCondition(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getActiveClaimConditionId(
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getClaimConditionById(
      _tokenId: PromiseOrValue<BigNumberish>,
      _conditionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSupplyClaimedByWallet(
      _tokenId: PromiseOrValue<BigNumberish>,
      _conditionId: PromiseOrValue<BigNumberish>,
      _claimer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setClaimConditions(
      _tokenId: PromiseOrValue<BigNumberish>,
      _conditions: IClaimCondition.ClaimConditionStruct[],
      _resetClaimEligibility: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    verifyClaim(
      _conditionId: PromiseOrValue<BigNumberish>,
      _claimer: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _quantity: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<string>,
      _pricePerToken: PromiseOrValue<BigNumberish>,
      _allowlistProof: IDrop1155.AllowlistProofStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
